default_stages: [pre-commit]
repos:
    # Common
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: mixed-line-ending
          - id: check-yaml
          - id: sort-simple-yaml

    - repo: https://github.com/compilerla/conventional-pre-commit
      rev: v4.2.0
      hooks:
          - id: conventional-pre-commit
            stages: [commit-msg]
            args: ['--verbose']

    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.10.0.1
      hooks:
          - id: shellcheck

    # Frontend

    - repo: local
      hooks:
          - id: prettier-npx
            name: prettier via npx
            entry: npx prettier --write
            language: system
            files: ^frontend/.*\.(js|jsx|ts|tsx|css|scss|json|md)$

    - repo: local
      hooks:
          - id: eslint
            name: ESLint
            entry: npx eslint -c frontend/eslint.config.cjs --no-warn-ignored
            language: system
            files: ^frontend/

    # Backend

    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.12.4
      hooks:
          # Run the linter.
          - id: ruff
            args: [--fix]
            files: ^backend/
          # Run the formatter.
          - id: ruff-format
            files: ^backend/

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.17.0
      hooks:
          - id: mypy
            args: ['--config-file=backend/mypy.ini', '--no-site-packages']
            files: ^backend/
