history_dir: ./history
summary_dir: ./summary
menu_dir: ./menu

notes_dir: ./notes
notes_max_char: 500

cafe_info_dir: ./cafe_info
cafei_nfo_max_char: 500

uvicorn_host: '0.0.0.0'
uvicorn_port: 80
uvicorn_workers: 1
uvicorn_reload: false

cors_allow_origins: ['http://localhost', 'http://frontend']

openai_model: gpt-4o-2024-08-06
openai_base_url: https://api.openai.com/v1
openai_temperature: 0.7
openai_max_tokens: 1000

openai_validator_model: gpt-4o-2024-08-06
openai_validator_base_url: https://api.openai.com/v1
openai_validator_temperature: 0.7
openai_validator_max_tokens: 1000

openai_summary_model: gpt-4o-2024-08-06
openai_summary_base_url: https://api.openai.com/v1
openai_summary_temperature: 0.7
openai_summary_max_tokens: 1000

openai_visual_model: gpt-4o-2024-08-06
openai_visual_base_url: https://api.openai.com/v1
openai_visual_temperature: 0.7
openai_visual_max_tokens: 10000

# Cookie
cookie_name: ofiik_cookie
cookie_max_age: 31536000 # 1 год
