FROM node:20-alpine AS builder

WORKDIR /workspace

COPY package.json package-lock.json ./
RUN npm install

COPY . /workspace
RUN npm run build

# 2. Serve stage
FROM nginx:alpine AS production

RUN rm -rf /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

COPY --from=builder /workspace/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
